# The URL the site will be built for
base_url = "https://wouterjehee.com"
title = "Wouter Jehee"

compile_sass = false
build_search_index = false

generate_robots_txt = true
generate_feeds = true


[markdown]
highlight_code = false
external_links_target_blank = true

[extra]
email = "contact@wouterjehee.com"
github = "https://github.com/wjehee"
keyoxide = "https://keyoxide.org/AA13CA644F601A1795DD6CB9F3D495E78205B9EF"
bluesky = "https://bsky.app/profile/wjehee.bsky.social"
intigriti = ""

